version: '3.8'

services:
  shop-it-pg:
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shop-it
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: